<?php

namespace app\modules\api\modules\v1;

/**
 * v1 module definition class
 */

use Yii;
use yii\base\BootstrapInterface;
use app\modules\base\Module as BaseModule;

class Module extends BaseModule
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'app\modules\api\modules\v1\controllers';

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();
        \Yii::configure($this, require(__DIR__ . '/config.php'));
    }
    public function beforeAction($action)
    {
        parent::setHeaders();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
