<?php

namespace app\modules\api\controllers;

use yii\rest\Controller;
use Yii;
use yii\web\Response;

/**
 * Default controller for the `api` module
 */
class DefaultController extends Controller
{
    protected $_post;

    public function init()
    {
        parent::init();

        Yii::$app->user->enableSession = false;
        Yii::$app->request->enableCsrfCookie = false;
        Yii::$app->request->enableCookieValidation = false;
    }
    
    public function actionError() {
        return new \yii\web\NotFoundHttpException("My customviews message");
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['contentNegotiator']['formats']['application/xml'] = Response::FORMAT_JSON;
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors; // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        if(!empty(\Yii::$app->request->getRawBody())){
            $this->_post = json_decode(\Yii::$app->request->getRawBody(), true);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}